############################################################################
#  We use make file as a shortcut to run the workflows locally in a docker #
#  container so we can test the workflows before pushing to github         #
############################################################################

# Get azure credentials

# Define the the docker image that will act as github runner

# Define set of commands to run the workflow